name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -o ./build/server main.go 


    - name: Test
      run: go test ./... -v -gcflags=-l

  push: 
    needs: build
    runs-on: "ubuntu-latest"
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: noisyboy9/devops-demo:latest

  deploy: 
    needs: push
    runs-on: "ubuntu-latest"
    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect and pull
        run: | 
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          docker login -u {{ secrets.DOCKERHUB_USERNAME }} -p {{ secrets.DOCKERHUB_PASSWORD }} && \ 
          docker ps -aq | xargs docker stop | xargs docker rm &&
          docker image pull noisyboy9/devops-demo:latest &&
          docker container run noisyboy9/devops-demo -p 80:8080"
